#!/usr/bin/env bash

#make sure pv is installed
if ! command -v pv &> /dev/null; then
  echo "pv command not found, please install pv to use this script"
  exit 1
fi

if [ -z "$input" ] || [ -z "$output" ]; then
  echo "Usage: $0 <input> <output>"
  exit 1
fi

input="$1"
output="$2"

# Get the size of the input file
size=$(du -b "$input" 2>/dev/null || blockdev --getsize64 "$input" 2>/dev/null)

if [ -z "$size" ]; then
  echo "error determining size of $input"
  exit 1
fi

bs=$(( 4 * 1024 * 1024 ))

echo "Size of $input: $(numfmt --to=iec-i --suffix=B "$size")"
echo "Starting transfer"

dd if="$input" status=none | pv -s "$size" | dd of="$output" bs="$bs" conv=fsync status=none

echo "It is done..."
